version: "3.7"

services:
  file-indexer:
    build:
      context: .
    working_dir: /opt/app/image/bin
    ports:
      - 25333:25333
    volumes:
      - ./documents:/home/app/documents/
    command: sh -c "./FileIndexer"
    tty: true
